/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "s21_matrix-test.check" instead.
 */

#include <check.h>

#line 1 "s21_matrix-test.check"
#include "s21_matrix.h"
#include <stdlib.h>
#define E 1e-8

START_TEST(s21_create_matrix_1) {
#line 6
    matrix_t actual = s21_create_matrix(2, 2);
    double expected[2][2] = { {0, 0}, {0, 0} };
    for (int i = 0; i < 2; i++) {
        for (int j = 0; j < 2; j++) {
            double error = fabs(actual.matrix[i][j] - expected[i][j]);
            ck_assert_double_lt(error, E);
        }
    }
    s21_remove_matrix(&actual);
}
END_TEST

START_TEST(s21_create_matrix_2) {
#line 16
    matrix_t actual = s21_create_matrix(2, 3);
    double expected[2][3] = { {0, 0, 0}, {0, 0, 0} };
    for (int i = 0; i < 2; i++) {
        for (int j = 0; j < 3; j++) {
            double error = fabs(actual.matrix[i][j] - expected[i][j]);
            ck_assert_double_lt(error, E);
        }
    }
    s21_remove_matrix(&actual);
}
END_TEST

START_TEST(s21_create_matrix_3) {
#line 26
    matrix_t actual = s21_create_matrix(3, 3);
    double expected[3][3] = { {0, 0, 0}, {0, 0, 0}, {0, 0, 0} };
    for (int i = 0; i < 3; i++) {
        for (int j = 0; j < 3; j++) {
            double error = fabs(actual.matrix[i][j] - expected[i][j]);
            ck_assert_double_lt(error, E);
        }
    }
    s21_remove_matrix(&actual);
}
END_TEST

START_TEST(s21_create_matrix_4) {
#line 36
    matrix_t actual = s21_create_matrix(-3, 3);
    ck_assert_int_eq(actual.matrix_type, 1);
}
END_TEST

START_TEST(s21_create_matrix_5) {
#line 39
    matrix_t actual = s21_create_matrix(0, 3);
    ck_assert_int_eq(actual.matrix_type, 1);
}
END_TEST

START_TEST(s21_remove_matrix_1) {
#line 42
    matrix_t actual = s21_create_matrix(2, 2);
    s21_remove_matrix(&actual);
    int expected = 1;
    ck_assert_int_eq(actual.matrix_type, expected);
}
END_TEST

START_TEST(s21_remove_matrix_2) {
#line 47
    matrix_t actual = s21_create_matrix(-2, 2);
    s21_remove_matrix(&actual);
    int expected = 1;
    ck_assert_int_eq(actual.matrix_type, expected);
}
END_TEST

START_TEST(s21_eq_matrix_1) {
#line 52
    matrix_t test1 = s21_create_matrix(2, 2);
    matrix_t test2 = s21_create_matrix(2, 2);
    int expected = 1;
    int actual = s21_eq_matrix(&test1, &test2);
    ck_assert_int_eq(actual, expected);
    s21_remove_matrix(&test1);
    s21_remove_matrix(&test2);
}
END_TEST

START_TEST(s21_eq_matrix_2) {
#line 60
    matrix_t test1 = s21_create_matrix(2, 2);
    matrix_t test2 = s21_create_matrix(2, 3);
    int expected = 0;
    int actual = s21_eq_matrix(&test1, &test2);
    ck_assert_int_eq(actual, expected);
    s21_remove_matrix(&test1);
    s21_remove_matrix(&test2);
}
END_TEST

START_TEST(s21_eq_matrix_3) {
#line 68
    matrix_t test1 = s21_create_matrix(1, 1);
    matrix_t test2 = s21_create_matrix(1, 1);
    test1.matrix[0][0] = 1;
    test2.matrix[0][0] = 1;
    int expected = 1;
    int actual = s21_eq_matrix(&test1, &test2);
    ck_assert_int_eq(actual, expected);
    s21_remove_matrix(&test1);
    s21_remove_matrix(&test2);
}
END_TEST

START_TEST(s21_eq_matrix_4) {
#line 78
    matrix_t test1 = s21_create_matrix(1, 1);
    matrix_t test2 = s21_create_matrix(1, 1);
    test1.matrix[0][0] = 2;
    test2.matrix[0][0] = 1;
    int expected = 0;
    int actual = s21_eq_matrix(&test1, &test2);
    ck_assert_int_eq(actual, expected);
    s21_remove_matrix(&test1);
    s21_remove_matrix(&test2);
}
END_TEST

START_TEST(s21_sum_matrix_1) {
#line 88
    matrix_t test1 = s21_create_matrix(1, 1);
    matrix_t test2 = s21_create_matrix(1, 1);
    test1.matrix[0][0] = 2;
    test2.matrix[0][0] = 1;
    double expected[1][1] = { { 3 } };
    matrix_t actual = s21_sum_matrix(&test1, &test2);
    double error = fabs(actual.matrix[0][0] - expected[0][0]);
    ck_assert_double_lt(error, E);
    s21_remove_matrix(&test1);
    s21_remove_matrix(&test2);
    s21_remove_matrix(&actual);
}
END_TEST

START_TEST(s21_sum_matrix_2) {
#line 100
    matrix_t test1 = s21_create_matrix(2, 2);
    matrix_t test2 = s21_create_matrix(2, 2);
    test1.matrix[0][0] = 2;
    test1.matrix[0][1] = 2;
    test1.matrix[1][0] = 2;
    test1.matrix[1][1] = 2;
    test2.matrix[0][0] = 2;
    test2.matrix[0][1] = 2;
    test2.matrix[1][0] = 2;
    test2.matrix[1][1] = 2;
    double expected[2][2] = { { 4, 4 }, { 4, 4 } };
    matrix_t actual = s21_sum_matrix(&test1, &test2);
    for (int i = 0; i < 2; i++) {
        for (int j = 0; j < 2; j++) {
            double error = fabs(actual.matrix[i][j] - expected[i][j]);
            ck_assert_double_lt(error, E);
        }
    }
    s21_remove_matrix(&test1);
    s21_remove_matrix(&test2);
    s21_remove_matrix(&actual);
}
END_TEST

START_TEST(s21_sum_matrix_3) {
#line 122
    matrix_t test1 = s21_create_matrix(1, 2);
    matrix_t test2 = s21_create_matrix(1, 1);
    matrix_t actual = s21_sum_matrix(&test1, &test2);
    ck_assert_int_eq(actual.matrix_type, 1);
    s21_remove_matrix(&test1);
    s21_remove_matrix(&test2);
}
END_TEST

START_TEST(s21_sub_matrix_1) {
#line 129
    matrix_t test1 = s21_create_matrix(1, 1);
    matrix_t test2 = s21_create_matrix(1, 1);
    test1.matrix[0][0] = 2;
    test2.matrix[0][0] = 1;
    double expected[1][1] = { { 1 } };
    matrix_t actual = s21_sub_matrix(&test1, &test2);
    double error = fabs(actual.matrix[0][0] - expected[0][0]);
    ck_assert_double_lt(error, E);
    s21_remove_matrix(&test1);
    s21_remove_matrix(&test2);
    s21_remove_matrix(&actual);
}
END_TEST

START_TEST(s21_sub_matrix_2) {
#line 141
    matrix_t test1 = s21_create_matrix(2, 2);
    matrix_t test2 = s21_create_matrix(2, 2);
    test1.matrix[0][0] = 2;
    test1.matrix[0][1] = 2;
    test1.matrix[1][0] = 2;
    test1.matrix[1][1] = 2;
    test2.matrix[0][0] = 2;
    test2.matrix[0][1] = 2;
    test2.matrix[1][0] = 2;
    test2.matrix[1][1] = 2;
    double expected[2][2] = { { 0, 0 }, { 0, 0 } };
    matrix_t actual = s21_sub_matrix(&test1, &test2);
    for (int i = 0; i < 2; i++) {
        for (int j = 0; j < 2; j++) {
            double error = fabs(actual.matrix[i][j] - expected[i][j]);
            ck_assert_double_lt(error, E);
        }
    }
    s21_remove_matrix(&test1);
    s21_remove_matrix(&test2);
    s21_remove_matrix(&actual);
}
END_TEST

START_TEST(s21_sub_matrix_3) {
#line 163
    matrix_t test1 = s21_create_matrix(1, 2);
    matrix_t test2 = s21_create_matrix(1, 1);
    matrix_t actual = s21_sub_matrix(&test1, &test2);
    ck_assert_int_eq(actual.matrix_type, 1);
    s21_remove_matrix(&test1);
    s21_remove_matrix(&test2);
}
END_TEST

START_TEST(s21_mult_number_1) {
#line 170
    matrix_t test1 = s21_create_matrix(1, 1);
    test1.matrix[0][0] = 2;
    double expected[1][1] = { { 4 } };
    matrix_t actual = s21_mult_number(&test1, 2);
    double error = fabs(actual.matrix[0][0] - expected[0][0]);
    ck_assert_double_lt(error, E);
    s21_remove_matrix(&test1);
    s21_remove_matrix(&actual);
}
END_TEST

START_TEST(s21_mult_number_2) {
#line 179
    matrix_t test1 = s21_create_matrix(2, 2);
    test1.matrix[0][0] = 2;
    test1.matrix[0][1] = 2;
    test1.matrix[1][0] = 2;
    test1.matrix[1][1] = 2;
    double expected[2][2] = { { 4, 4 }, { 4, 4 } };
    matrix_t actual = s21_mult_number(&test1, 2);
    for (int i = 0; i < 2; i++) {
        for (int j = 0; j < 2; j++) {
            double error = fabs(actual.matrix[i][j] - expected[i][j]);
            ck_assert_double_lt(error, E);
        }
    }
    s21_remove_matrix(&test1);
    s21_remove_matrix(&actual);
}
END_TEST

START_TEST(s21_mult_number_3) {
#line 195
    matrix_t test1 = s21_create_matrix(-2, 2);
    matrix_t actual = s21_mult_number(&test1, 2);
    ck_assert_int_eq(actual.matrix_type, 1);
    s21_remove_matrix(&test1);
}
END_TEST

START_TEST(s21_mult_matrix_1) {
#line 200
    matrix_t test1 = s21_create_matrix(1, 1);
    matrix_t test2 = s21_create_matrix(1, 1);
    test1.matrix[0][0] = 2;
    test2.matrix[0][0] = 1;
    double expected[1][1] = { { 2 } };
    matrix_t actual = s21_mult_matrix(&test1, &test2);
    double error = fabs(actual.matrix[0][0] - expected[0][0]);
    ck_assert_double_lt(error, E);
    s21_remove_matrix(&test1);
    s21_remove_matrix(&test2);
    s21_remove_matrix(&actual);
}
END_TEST

START_TEST(s21_mult_matrix_2) {
#line 212
    matrix_t test1 = s21_create_matrix(1, 2);
    matrix_t test2 = s21_create_matrix(2, 1);
    test1.matrix[0][0] = 2;
    test1.matrix[0][1] = 3;
    test2.matrix[0][0] = 1;
    test2.matrix[1][0] = 5;
    double expected[1][1] = { { 17 } };
    matrix_t actual = s21_mult_matrix(&test1, &test2);
    double error = fabs(actual.matrix[0][0] - expected[0][0]);
    ck_assert_double_lt(error, E);
    s21_remove_matrix(&test1);
    s21_remove_matrix(&test2);
    s21_remove_matrix(&actual);
}
END_TEST

START_TEST(s21_mult_matrix_3) {
#line 226
    matrix_t test1 = s21_create_matrix(2, 1);
    matrix_t test2 = s21_create_matrix(1, 2);
    test1.matrix[0][0] = 2;
    test1.matrix[1][0] = 3;
    test2.matrix[0][0] = 1;
    test2.matrix[0][1] = 5;
    double expected[2][2] = { { 2, 10 }, { 3, 15 } };
    matrix_t actual = s21_mult_matrix(&test1, &test2);
    double error = fabs(actual.matrix[0][0] - expected[0][0]);
    ck_assert_double_lt(error, E);
    s21_remove_matrix(&test1);
    s21_remove_matrix(&test2);
    s21_remove_matrix(&actual);
}
END_TEST

START_TEST(s21_mult_matrix_4) {
#line 240
    matrix_t test1 = s21_create_matrix(2, 2);
    matrix_t test2 = s21_create_matrix(1, 2);
    matrix_t actual = s21_mult_matrix(&test1, &test2);
    ck_assert_int_eq(actual.matrix_type, 1);
    s21_remove_matrix(&test1);
    s21_remove_matrix(&test2);
    s21_remove_matrix(&actual);
}
END_TEST

START_TEST(s21_transpose_1) {
#line 248
    matrix_t test1 = s21_create_matrix(1, 3);
    matrix_t expected = s21_create_matrix(3, 1);
    matrix_t actual = s21_transpose(&test1);
    for (int i = 0; i < 3; i++) {
        for (int j = 0; j < 1; j++) {
            double error = fabs(actual.matrix[i][j] - expected.matrix[i][j]);
            ck_assert_double_lt(error, E);
        }
    }
    s21_remove_matrix(&test1);
    s21_remove_matrix(&expected);
    s21_remove_matrix(&actual);
}
END_TEST

START_TEST(s21_transpose_2) {
#line 261
    matrix_t test1 = s21_create_matrix(3, 15);
    matrix_t expected = s21_create_matrix(15, 3);
    matrix_t actual = s21_transpose(&test1);
    for (int i = 0; i < 15; i++) {
        for (int j = 0; j < 3; j++) {
            double error = fabs(actual.matrix[i][j] - expected.matrix[i][j]);
            ck_assert_double_lt(error, E);
        }
    }
    s21_remove_matrix(&test1);
    s21_remove_matrix(&expected);
    s21_remove_matrix(&actual);
}
END_TEST

START_TEST(s21_transpose_3) {
#line 274
    matrix_t test1 = s21_create_matrix(2, 2);
    test1.matrix[0][0] = 1;
    test1.matrix[0][1] = 2;
    test1.matrix[1][0] = 3;
    test1.matrix[1][1] = 4;
    matrix_t expected = s21_create_matrix(2, 2);
    expected.matrix[0][0] = 1;
    expected.matrix[0][1] = 3;
    expected.matrix[1][0] = 2;
    expected.matrix[1][1] = 4;
    matrix_t actual = s21_transpose(&test1);
    for (int i = 0; i < 2; i++) {
        for (int j = 0; j < 2; j++) {
            double error = fabs(actual.matrix[i][j] - expected.matrix[i][j]);
            ck_assert_double_lt(error, E);
        }
    }
    s21_remove_matrix(&test1);
    s21_remove_matrix(&expected);
    s21_remove_matrix(&actual);
}
END_TEST

START_TEST(s21_transpose_4) {
#line 295
    matrix_t test1 = s21_create_matrix(2, 3);
    test1.matrix[0][0] = 1;
    test1.matrix[0][1] = 2;
    test1.matrix[0][2] = 3;
    test1.matrix[1][0] = 4;
    test1.matrix[1][1] = 5;
    test1.matrix[1][2] = 6;
    matrix_t expected = s21_create_matrix(3, 2);
    expected.matrix[0][0] = 1;
    expected.matrix[0][1] = 4;
    expected.matrix[1][0] = 2;
    expected.matrix[1][1] = 5;
    expected.matrix[2][0] = 3;
    expected.matrix[2][1] = 6;
    matrix_t actual = s21_transpose(&test1);
    for (int i = 0; i < 3; i++) {
        for (int j = 0; j < 2; j++) {
            double error = fabs(actual.matrix[i][j] - expected.matrix[i][j]);
            ck_assert_double_lt(error, E);
        }
    }
    s21_remove_matrix(&test1);
    s21_remove_matrix(&expected);
    s21_remove_matrix(&actual);
}
END_TEST

START_TEST(s21_determinant_1) {
#line 320
    matrix_t test1 = s21_create_matrix(2, 2);
    test1.matrix[0][0] = 1;
    test1.matrix[0][1] = 2;
    test1.matrix[1][0] = 3;
    test1.matrix[1][1] = 4;
    double expected = -2.0;
    double actual = s21_determinant(&test1);
    double error = fabs(actual - expected);
    ck_assert_double_lt(error, E);
    s21_remove_matrix(&test1);
}
END_TEST

START_TEST(s21_determinant_2) {
#line 331
    matrix_t test1 = s21_create_matrix(3, 3);
    test1.matrix[0][0] = 1;
    test1.matrix[0][1] = 2;
    test1.matrix[0][2] = 3;
    test1.matrix[1][0] = 4;
    test1.matrix[1][1] = 5;
    test1.matrix[1][2] = 6;
    test1.matrix[2][0] = 7;
    test1.matrix[2][1] = 8;
    test1.matrix[2][2] = 9;
    double expected = 0;
    double actual = s21_determinant(&test1);
    double error = fabs(actual - expected);
    ck_assert_double_lt(error, E);
    s21_remove_matrix(&test1);
}
END_TEST

START_TEST(s21_determinant_3) {
#line 347
    matrix_t test1 = s21_create_matrix(4, 4);
    test1.matrix[0][0] = 124;
    test1.matrix[0][1] = 78;
    test1.matrix[0][2] = 45;
    test1.matrix[0][3] = 23;
    test1.matrix[1][0] = 78;
    test1.matrix[1][1] = 6;
    test1.matrix[1][2] = 313;
    test1.matrix[1][3] = 31;
    test1.matrix[2][0] = 14;
    test1.matrix[2][1] = 141;
    test1.matrix[2][2] = 414;
    test1.matrix[2][3] = 14;
    test1.matrix[3][0] = 632;
    test1.matrix[3][1] = 6;
    test1.matrix[3][2] = 1414;
    test1.matrix[3][3] = 41;
    double expected = 1085952102;
    double actual = s21_determinant(&test1);
    double error = fabs(actual - expected);
    ck_assert_double_lt(error, E);
    s21_remove_matrix(&test1);
}
END_TEST

START_TEST(s21_determinant_4) {
#line 370
    matrix_t test1 = s21_create_matrix(3, 2);
    double actual = s21_determinant(&test1);
    ck_assert_double_ne(actual, actual);
    s21_remove_matrix(&test1);
}
END_TEST

START_TEST(s21_determinant_5) {
#line 375
    matrix_t test1 = s21_create_matrix(1, 1);
    test1.matrix[0][0] = 1;
    double expected = 1;
    double actual = s21_determinant(&test1);
    double error = fabs(actual - expected);
    ck_assert_double_lt(error, E);
    s21_remove_matrix(&test1);
}
END_TEST

START_TEST(s21_calc_complements_1) {
#line 383
    matrix_t test1 = s21_create_matrix(2, 2);
    test1.matrix[0][0] = 1;
    test1.matrix[0][1] = 2;
    test1.matrix[1][0] = 3;
    test1.matrix[1][1] = 4;
    double expected[2][2] = { { 4, -3 }, { -2, 1 } };
    matrix_t actual = s21_calc_complements(&test1);
    for (int i = 0; i < 2; i++) {
        for (int j = 0; j < 2; j++) {
            double error = fabs(actual.matrix[i][j] - expected[i][j]);
            ck_assert_double_lt(error, E);
        }
    }
    s21_remove_matrix(&test1);
    s21_remove_matrix(&actual);
}
END_TEST

START_TEST(s21_calc_complements_2) {
#line 399
    matrix_t test1 = s21_create_matrix(3, 3);
    test1.matrix[0][0] = 2;
    test1.matrix[0][1] = 3;
    test1.matrix[0][2] = 1;
    test1.matrix[1][0] = 5;
    test1.matrix[1][1] = 9;
    test1.matrix[1][2] = 1;
    test1.matrix[2][0] = 4;
    test1.matrix[2][1] = 7;
    test1.matrix[2][2] = 2;
    double expected[3][3] = { { 11, -6, -1 }, { 1, 0, -2 }, { -6, 3, 3 } };
    matrix_t actual = s21_calc_complements(&test1);
    for (int i = 0; i < 3; i++) {
        for (int j = 0; j < 3; j++) {
            double error = fabs(actual.matrix[i][j] - expected[i][j]);
            ck_assert_double_lt(error, E);
        }
    }
    s21_remove_matrix(&test1);
    s21_remove_matrix(&actual);
}
END_TEST

START_TEST(s21_calc_complements_3) {
#line 420
    matrix_t test1 = s21_create_matrix(2, 3);
    matrix_t actual = s21_calc_complements(&test1);
    ck_assert_int_eq(actual.matrix_type, 1);
    s21_remove_matrix(&test1);
}
END_TEST

START_TEST(s21_inverse_matrix_1) {
#line 425
    matrix_t test1 = s21_create_matrix(2, 2);
    test1.matrix[0][0] = 1;
    test1.matrix[0][1] = 2;
    test1.matrix[1][0] = 3;
    test1.matrix[1][1] = 4;
    double expected[2][2] = { { -2, 1 }, { 1.5, -0.5 } };
    matrix_t actual = s21_inverse_matrix(&test1);
    for (int i = 0; i < 2; i++) {
        for (int j = 0; j < 2; j++) {
            double error = fabs(actual.matrix[i][j] - expected[i][j]);
            ck_assert_double_lt(error, E);
        }
    }
    s21_remove_matrix(&test1);
    s21_remove_matrix(&actual);
}
END_TEST

START_TEST(s21_inverse_matrix_2) {
#line 441
    matrix_t test1 = s21_create_matrix(3, 3);
    test1.matrix[0][0] = 2;
    test1.matrix[0][1] = 3;
    test1.matrix[0][2] = 1;
    test1.matrix[1][0] = 5;
    test1.matrix[1][1] = 9;
    test1.matrix[1][2] = 1;
    test1.matrix[2][0] = 4;
    test1.matrix[2][1] = 7;
    test1.matrix[2][2] = 2;
    double expected[3][3] = { { 3.66666666, 0.33333333, -2 }, { -2, 0, 1 }, { -0.33333333, -0.66666666, 1 } };
    matrix_t actual = s21_inverse_matrix(&test1);
    for (int i = 0; i < 3; i++) {
        for (int j = 0; j < 3; j++) {
            double error = fabs(actual.matrix[i][j] - expected[i][j]);
            ck_assert_double_lt(error, E);
        }
    }
    s21_remove_matrix(&test1);
    s21_remove_matrix(&actual);
}
END_TEST

START_TEST(s21_inverse_matrix_3) {
#line 462
    matrix_t test1 = s21_create_matrix(2, 3);
    matrix_t actual = s21_inverse_matrix(&test1);
    ck_assert_int_eq(actual.matrix_type, 1);
    s21_remove_matrix(&test1);
    s21_remove_matrix(&actual);
}
END_TEST

START_TEST(s21_inverse_matrix_4) {
#line 468
    matrix_t test1 = s21_create_matrix(2, 2);
    test1.matrix[0][0] = 0;
    test1.matrix[0][1] = 0;
    test1.matrix[1][0] = 0;
    test1.matrix[1][1] = 0;
    matrix_t actual = s21_inverse_matrix(&test1);
    ck_assert_int_eq(actual.matrix_type, 1);
    s21_remove_matrix(&test1);
    s21_remove_matrix(&actual);
}
END_TEST

START_TEST(s21_inverse_matrix_5) {
#line 478
    matrix_t test1 = s21_create_matrix(1, 1);
    test1.matrix[0][0] = 5;
    double expected = 0.2;
    matrix_t actual = s21_inverse_matrix(&test1);
    double error = fabs(actual.matrix[0][0] - expected);
    ck_assert_double_lt(error, E);
    s21_remove_matrix(&test1);
    s21_remove_matrix(&actual);
}
END_TEST

int main(void) {
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;
    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, s21_create_matrix_1);
    tcase_add_test(tc1_1, s21_create_matrix_2);
    tcase_add_test(tc1_1, s21_create_matrix_3);
    tcase_add_test(tc1_1, s21_create_matrix_4);
    tcase_add_test(tc1_1, s21_create_matrix_5);
    tcase_add_test(tc1_1, s21_remove_matrix_1);
    tcase_add_test(tc1_1, s21_remove_matrix_2);
    tcase_add_test(tc1_1, s21_eq_matrix_1);
    tcase_add_test(tc1_1, s21_eq_matrix_2);
    tcase_add_test(tc1_1, s21_eq_matrix_3);
    tcase_add_test(tc1_1, s21_eq_matrix_4);
    tcase_add_test(tc1_1, s21_sum_matrix_1);
    tcase_add_test(tc1_1, s21_sum_matrix_2);
    tcase_add_test(tc1_1, s21_sum_matrix_3);
    tcase_add_test(tc1_1, s21_sub_matrix_1);
    tcase_add_test(tc1_1, s21_sub_matrix_2);
    tcase_add_test(tc1_1, s21_sub_matrix_3);
    tcase_add_test(tc1_1, s21_mult_number_1);
    tcase_add_test(tc1_1, s21_mult_number_2);
    tcase_add_test(tc1_1, s21_mult_number_3);
    tcase_add_test(tc1_1, s21_mult_matrix_1);
    tcase_add_test(tc1_1, s21_mult_matrix_2);
    tcase_add_test(tc1_1, s21_mult_matrix_3);
    tcase_add_test(tc1_1, s21_mult_matrix_4);
    tcase_add_test(tc1_1, s21_transpose_1);
    tcase_add_test(tc1_1, s21_transpose_2);
    tcase_add_test(tc1_1, s21_transpose_3);
    tcase_add_test(tc1_1, s21_transpose_4);
    tcase_add_test(tc1_1, s21_determinant_1);
    tcase_add_test(tc1_1, s21_determinant_2);
    tcase_add_test(tc1_1, s21_determinant_3);
    tcase_add_test(tc1_1, s21_determinant_4);
    tcase_add_test(tc1_1, s21_determinant_5);
    tcase_add_test(tc1_1, s21_calc_complements_1);
    tcase_add_test(tc1_1, s21_calc_complements_2);
    tcase_add_test(tc1_1, s21_calc_complements_3);
    tcase_add_test(tc1_1, s21_inverse_matrix_1);
    tcase_add_test(tc1_1, s21_inverse_matrix_2);
    tcase_add_test(tc1_1, s21_inverse_matrix_3);
    tcase_add_test(tc1_1, s21_inverse_matrix_4);
    tcase_add_test(tc1_1, s21_inverse_matrix_5);
    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);
    return nf == 0 ? 0 : 1;
}
